### ISSUE TITLE
Project 5 grading notes

### ISSUE THREAD

**Issue by janetlndavis** [WhitmanSWDesignSpring2017/Heisenbug#13]
I'm not able to make a pull request from your release. However, you can see [my comparison to the release branch here.](https://github.com/WhitmanSWDesignSpring2017/Heisenbug/compare/V2.0...project5-grading) And [here is a direct link to the grading rubric](https://github.com/WhitmanSWDesignSpring2017/Heisenbug/blob/159dc1bd82e05e2759e8a495aac42256ed0eea80/rubric.md) .

I don't expect you to respond to all these issues in Project 6 since you are receiving feedback so close to the deadline. However, I would like you to tag your release as **project6-release**, provide me with an image of your UML diagram, and complete the reflection to the best of your ability.

**Comment by pablofernandezcom** [comment]
I added your username to the list of project administrator. This should fix the pull request issue going forward.
